// English translations for app-owned Chinese display keys. Keep placeholders unchanged.
enum EnglishStrings {
    static let values: [String: String] = [
        "已连接": "Connected",
        "连接正常，持续心跳": "Connected; heartbeat active",
        "已保存": "Saved",
        "配置：点开可加载/新增；界面改动自动存到当前配置": "Load or add profiles. Changes are saved to the current profile automatically.",
        "切换 日间 / 夜间": "Switch light / dark appearance",
        "型号": "Model",
        "固件": "Firmware",
        "⚡充电": "⚡ Charging",
        "电量": "Battery",
        "查看完整设备信息": "View device information",
        "电源：待机 / 休眠 / 重启": "Power: standby, sleep and restart",
        "按键自检：确认设备有没有真的发出按键": "Check whether the device is sending key reports",
        "设备信息": "Device Information",
        "序列号": "Serial number",
        "{0} ⚡充电中": "{0} ⚡ Charging",
        "灯效模式": "Mode",
        "全灭": "Off",
        "全亮": "All on",
        "工作": "Active",
        "灯效亮度": "Brightness",
        "灭": "Off",
        "低": "Low",
        "高": "High",
        "配置": "Profiles",
        "界面上的改动会自动存到当前配置。可新增多套、随时加载。": "Changes are saved to the current profile automatically. Add and load profiles here.",
        "当前": "Current",
        "新增配置名，如 工作": "New profile name, e.g. Work",
        "新增": "Add",
        "暂无配置": "No profiles yet",
        "更新于 ": "Updated ",
        "尚未更新": "Not updated yet",
        "加载": "Load",
        "刚刚": "Just now",
        "{0} 分钟前": "{0} min ago",
        "{0} 小时前": "{0} hr ago",
        "「打开 App」绑定 · 仍在生效": "App Shortcuts · Still Active",
        "设备虽然没连上，但 Open VibeKey 还在运行——下面这些组合键仍然被本程序全局截获。": "The device is disconnected, but Open VibeKey is still running and listening for these global shortcuts.",
        "哨兵键 {0} 没能注册上，此绑定当前不生效。": "Could not register hotkey {0}. This binding is inactive.",
        "哨兵键 {0}": "Hotkey {0}",
        "解绑": "Unbind",
        "设备连上后，已解绑槽位上残留的哨兵键会被自动清掉。": "Unused hotkeys will be cleared from the device when it reconnects.",
        "快捷键 · 每键一个 · 离线生效": "Shortcuts · Saved on Device",
        "旋钮": "Dial",
        "标定": "Calibrate",
        "唤醒": "Wake",
        "闲置后厂商口可能对所有命令无响应，发一条心跳试探能否唤醒": "Send a heartbeat to try waking an idle configuration channel.",
        "唤醒中…": "Waking…",
        "已恢复": "Responding again",
        "仍无响应": "Still no response",
        "旋钮标定": "Dial Calibration",
        "旋钮转动/按下会发出 index 3–15 的快捷键，但物理动作↔index 的对应需实测。用下面「写数字标记」最快：": "Dial actions use shortcut indices 3–15. Identify each action with the number markers below:",
        "① 点「写数字标记」——把 index 3–9 分别设成数字键 3–9（物理按键 0/1/2 不动）。": "1. Write number markers: assign keys 3–9 to indices 3–9. Physical buttons 0–2 stay unchanged.",
        "② 光标放进任意输入框（备忘录/搜索框）。": "2. Focus any text field, such as Notes or a search box.",
        "③ 分别 左转 / 右转 / 按下 旋钮，看各自打出哪个数字，那就是该动作的 index。": "3. Turn left, turn right and press the dial. Each typed number is that action's index.",
        "④ 把三个 index 填到下方，再回到旋钮卡片给每个方向配上真正想要的键。": "4. Enter the three indices below, then assign your desired shortcuts in the dial card.",
        "写数字标记 3–9": "Write Markers 3–9",
        "探测 index 0–9": "Probe Indices 0–9",
        "左转": "Turn Left",
        "右转": "Turn Right",
        "按下": "Press",
        "灯效 · 全局": "Lighting · Global",
        "模式 / 亮度": "Mode / brightness",
        "工作模式各灯": "Lights in active mode",
        "按钮 1": "Button 1",
        "按钮 2": "Button 2",
        "按钮 3": "Button 3",
        "常亮": "Steady",
        "呼吸": "Pulse",
        "1 分钟": "1 min",
        "3 分钟": "3 min",
        "5 分钟": "5 min",
        "10 分钟": "10 min",
        "30 分钟": "30 min",
        "1 小时": "1 hr",
        "2 小时": "2 hr",
        "4 小时": "4 hr",
        "电源": "Power",
        "待机时长": "Standby",
        "{0} 秒": "{0} sec",
        "休眠时长": "Sleep",
        "待机＝息屏低功耗，按键可唤醒；休眠更深一级。调长更跟手，代价是耗电。": "Standby turns off the display; a key wakes it. Sleep saves more power. Longer delays improve responsiveness but use more battery.",
        "正在重启…": "Restarting…",
        "重启设备": "Restart Device",
        "会短暂断连，自动重连": "Disconnects briefly, then reconnects",
        "重启 VibeKey？": "Restart VibeKey?",
        "取消": "Cancel",
        "重启": "Restart",
        "设备会断开几秒后自动重连。已写入设备的快捷键和设置不受影响。": "The device will disconnect for a few seconds and reconnect automatically. Saved shortcuts and settings will be kept.",
        "按键自检": "Key Diagnostics",
        "检查设备有没有真的把按键发给电脑。接收器的转发通道偶尔会卡死——那时 USB、配置、电量全都正常，唯独按键一个都出不来。": "Check whether the device sends keys to your Mac. The receiver can stop forwarding keys even when its connection, settings and battery readings work.",
        "开始自检": "Start Check",
        "设备未在线，请先长按开机。": "The device is offline. Press and hold its power button first.",
        "请现在按一下 VibeKey 任意键，或转一下旋钮": "Press any VibeKey button or turn the dial now.",
        "剩余 {0} 秒": "{0} seconds remaining",
        "再测一次": "Check Again",
        "✅ 设备正常，窗口内发出了 {0} 个按键报告。": "✅ Device working: received {0} key reports during the check.",
        "如果你仍觉得某个键「没反应」，那是它配的功能在当前应用里没有可见效果——比如 ⌘. 或 Esc 在桌面上按下去本来就什么都不会发生。当前配置：": "A shortcut may have no visible effect in the current app. For example, ⌘. or Esc may do nothing on the desktop. Current shortcuts:",
        "❌ 设备在线（电量读得到），但一个按键报告都没发出。": "❌ Device online, but no key reports received.",
        "这是接收器的按键转发通道卡死了。**把 2.4G 接收器拔下来再插回去**即可恢复，配置和快捷键都不会丢。": "The receiver has stopped forwarding keys. Unplug and reconnect the 2.4G receiver. Your settings and shortcuts will be kept.",
        "无法判定：设备当前不在线。": "Cannot determine: device offline.",
        "设备不在线时零上报什么都证明不了。请先长按开机，再重新自检。": "No reports are expected while offline. Press and hold to power on, then check again.",
        "基线作废：接收器中途重新枚举过。": "Check interrupted: receiver reconnected.",
        "刚刚发生过拔插或掉线重连，系统的上报计数已归零。请重新自检。": "The receiver reconnected and the report counter reset. Please check again.",
        "自检不可用：读不到系统的 HID 上报计数。": "Diagnostics unavailable: cannot read the HID report counter.",
        "此状态计数在系统更新后可能不可用。设备本身不受影响。": "This status counter may become unavailable after macOS updates. The device itself is unaffected.",
        "麦克风": "Microphone",
        "开关 / 降噪 / 收音大小": "Power / noise reduction / gain",
        "设备麦克风开关": "Device microphone",
        "降噪": "Noise filter",
        "关": "Off",
        "中": "Med",
        "收音音量": "Input volume",
        "不支持": "Unavailable",
        "系统麦克风": "System Microphone",
        "当前录音设备": "Current input device",
        "刷新": "Refresh",
        "切换到": "Use",
        "插着时锁定为「{0}」": "Lock to “{0}” while connected",
        "🔒 已锁定：当前正用「{0}」（被切走会自动切回）": "🔒 Locked to “{0}”; switches back automatically.",
        "🔒 锁定中…正在切回「{0}」": "🔒 Switching back to “{0}”…",
        "未锁定：系统输入可自由切换": "Unlocked: system input can change freely.",
        "停止": "Stop",
        "测试": "Test",
        "需麦克风权限": "Microphone permission required",
        "电平测试需打包成 .app 后可用": "Level testing requires the packaged app.",
        "正在连接 VibeKey…": "Connecting to VibeKey…",
        "未连接": "Disconnected",
        "把 VibeKey 的连接器插上 · 关闭原厂 App，然后点下方「连接设备」": "Plug in the VibeKey receiver, close the official app, then click Connect Device.",
        "连接设备": "Connect Device",
        "失败": "Failed",
        "AU05 没有响应": "AU05 Not Responding",
        "连接器已插好，但设备的配置通道没有回应。两种可能：": "The receiver is connected, but the configuration channel is not responding. Two possible reasons:",
        "设备在待机": "Device on standby",
        "转一下旋钮或按一下按键就能唤醒。待机时按键照常生效，休眠的只是配置通道。": "Turn the dial or press a button to wake it. Keys still work on standby; only the configuration channel sleeps.",
        "设备没开机": "Device powered off",
        "长按开机。": "Press and hold to power on.",
        "恢复后会自动读取序列号 / 固件 / 电量并加载你的配置。": "Device details and your profile will load automatically when it responds.",
        "持续检测中…": "Checking for device…",
        "尝试唤醒": "Try Waking",
        "发一条心跳试探能否把待机的配置通道叫醒；叫不醒就得物理转一下旋钮": "Send a heartbeat to wake the configuration channel. If that fails, turn the physical dial.",
        "重新检测": "Check Again",
        "仍无响应——请转一下旋钮或按一下按键": "Still no response — turn the dial or press a button.",
        "未设置": "Not set",
        "主键": "Key",
        "选择另一个 App…": "Choose Another App…",
        "打开 App…": "Open App…",
        "清除": "Clear",
        "找不到该 App，可能已被卸载。重新选一个目标。": "App not found. It may have been removed. Choose another app.",
        "设备图缺失": "Device image missing",
        "等待 AU05 开机": "Waiting for AU05",
        "输入设备": "Input Devices",
        "刷新设备列表": "Refresh input devices",
        "开机时启动": "Launch at login",
        "开机启动设置失败：{0}": "Could not change launch at login: {0}",
        "需打包成 .app 后可用": "Requires the packaged app.",
        "打开设置…": "Open Settings…",
        "退出 Open VibeKey": "Quit Open VibeKey",
        "已锁定为 {0}，点击解锁": "Locked to {0}. Click to unlock.",
        "锁定为 {0}": "Lock to {0}",
        "选择要打开的 App": "Choose an App to Open",
        "搜索名称或 Bundle ID": "Search name or bundle ID",
        "正在枚举…": "Loading apps…",
        "没有匹配的 App": "No matching apps",
        "装在非常规位置的 App 请用下方「从文件选择…」": "For apps in other locations, use Choose from File below.",
        "从文件选择…": "Choose from File…",
        "选择": "Choose",
        "在 GitHub 上查看 OpenVibeKey": "View OpenVibeKey on GitHub",
        "打开 OpenVibeKey 的 GitHub 仓库": "Open the OpenVibeKey GitHub repository",
        "音量+": "Volume Up",
        "音量-": "Volume Down",
        "静音/解除静音": "Mute / Unmute",
        "播放/暂停": "Play / Pause",
        "下一曲": "Next Track",
        "上一曲": "Previous Track",
        "空格": "Space",
        "内置": "Built-in",
        "蓝牙": "Bluetooth",
        "虚拟": "Virtual",
        "读取中…": "Reading…",
        "默认": "Default",
        "连接中…": "Connecting…",
        "连接失败，请重试": "Connection failed. Please try again.",
        "已插好连接器，等待 AU05 开机…": "Receiver connected. Waiting for AU05 to power on…",
        "已连接 VibeKey": "Connected to VibeKey",
        "连接器已拔出": "Receiver disconnected",
        "AU05 未开机（连接器仍在）": "AU05 powered off (receiver connected)",
        "打开 App：{0}": "Open App: {0}",
        "媒体键": "Media key",
        "（空槽）": "(Empty)",
        "无响应": "No response",
        "已标记为数字键 {0}": "Assigned number key {0}",
        "按钮 {0}": "Button {0}",
        "旋钮左转": "Dial left",
        "旋钮右转": "Dial right",
        "旋钮按下": "Dial press",
        "旋钮 {0}": "Dial {0}",
        "这些按键没能写进设备：{0}。": "Could not save these keys to the device: {0}.",
        "多半是固件丢帧或接收器转发异常——重新插拔接收器，或在界面上改一下该键即可重试。": "Reconnect the receiver or edit the key to retry; the firmware or receiver may have dropped the command.",
        "哨兵键已用尽——池里 14 个组合都注册不上，暂时无法绑定「{0}」。": "All 14 hotkeys are unavailable. Cannot bind “{0}” right now.",
        "旋钮 · {0}": "Dial · {0}",
        "找不到「{0}」，它可能已被卸载。请重新选择目标 App。": "Cannot find “{0}”. It may have been removed. Please choose another app.",
        "（未知）": "(Unknown)",
        "语言": "Language",
        "跟随系统": "System Default",
        "哨兵键已自动更换：{0}": "Hotkeys automatically reassigned: {0}",
        "哨兵键已用尽，「{0}」暂时失效。请清除部分 App 绑定后重试。": "No hotkeys available for “{0}”. Remove some app bindings and try again.",
    ]
}
